import {
  Banana,
  Bath,
  Bean,
  Box,
  Candy,
  Cherry,
  Circle,
  CircleDot,
  Citrus,
  Coffee,
  Cookie,
  CupSoda,
  Cylinder,
  Droplet,
  Droplets,
  Flame,
  FlaskConical,
  Flower2,
  Funnel,
  Hand,
  Layers,
  Leaf,
  Milk,
  MilkOff,
  Mountain,
  Nut,
  Package,
  Paintbrush,
  Paperclip,
  ScrollText,
  Shirt,
  ShoppingBag,
  Sparkles,
  SprayCan,
  Sprout,
  Sun,
  Trash2,
  Utensils,
  Wheat,
} from 'lucide-react';

const ICONS = {
  banana: Banana,
  bath: Bath,
  bean: Bean,
  box: Box,
  candy: Candy,
  cherry: Cherry,
  circle: Circle,
  circleDot: CircleDot,
  citrus: Citrus,
  coffee: Coffee,
  cookie: Cookie,
  cupSoda: CupSoda,
  cylinder: Cylinder,
  droplet: Droplet,
  droplets: Droplets,
  flame: Flame,
  flaskConical: FlaskConical,
  flower2: Flower2,
  funnel: Funnel,
  hand: Hand,
  layers: Layers,
  leaf: Leaf,
  milk: Milk,
  milkOff: MilkOff,
  mountain: Mountain,
  nut: Nut,
  package: Package,
  paintbrush: Paintbrush,
  paperclip: Paperclip,
  scrollText: ScrollText,
  shirt: Shirt,
  shoppingBag: ShoppingBag,
  sparkles: Sparkles,
  sprayCan: SprayCan,
  sprout: Sprout,
  sun: Sun,
  trash2: Trash2,
  utensils: Utensils,
  wheat: Wheat,
};

export function Icon({ name, size = 18, strokeWidth = 1.75, className = 'icon' }) {
  const Cmp = ICONS[name] || Package;
  return <Cmp size={size} strokeWidth={strokeWidth} className={className} aria-hidden />;
}
